/**
 * Static content pools that feed the 90-day plan generator.
 * Each pool is read-only — the generator selects deterministically by day index.
 */

export const DSA_PROBLEMS: ReadonlyArray<readonly [string, string]> = [
  ["Two Sum", "HashMap lookup"],
  ["Valid Anagram", "Frequency map"],
  ["Contains Duplicate", "HashSet"],
  ["Best Time to Buy/Sell Stock", "One-pass minimum"],
  ["Valid Palindrome", "Two pointers"],
  ["Merge Sorted Array", "Reverse two pointers"],
  ["Move Zeroes", "Stable two pointers"],
  ["Binary Search", "Bounds discipline"],
  ["Search Insert Position", "Binary search variant"],
  ["First Bad Version", "Monotonic predicate"],
  ["Valid Parentheses", "Stack"],
  ["Min Stack", "Auxiliary stack"],
  ["Implement Queue using Stacks", "Stack/queue design"],
  ["Longest Common Prefix", "String scan"],
  ["Isomorphic Strings", "Bidirectional map"],
  ["Top K Frequent Elements", "Heap/bucket"],
  ["Group Anagrams", "Hashing canonical key"],
  ["Product of Array Except Self", "Prefix/suffix"],
  ["3Sum", "Sort plus two pointers"],
  ["Container With Most Water", "Two pointer proof"],
  ["Longest Substring Without Repeating", "Sliding window"],
  ["Find All Anagrams", "Window frequency"],
  ["Minimum Size Subarray Sum", "Shrinking window"],
  ["Search in Rotated Sorted Array", "Binary search decision"],
  ["Find Minimum in Rotated Array", "Binary search invariant"],
  ["Koko Eating Bananas", "Answer-space binary search"],
  ["Linked List Cycle", "Fast/slow pointer"],
  ["Reverse Linked List", "Pointer reversal"],
  ["Merge Two Sorted Lists", "Sentinel node"],
  ["Remove Nth Node From End", "Two pointer gap"],
  ["Maximum Depth of Binary Tree", "DFS recursion"],
  ["Invert Binary Tree", "Tree traversal"],
  ["Binary Tree Level Order", "BFS queue"],
  ["Diameter of Binary Tree", "Post-order height"],
  ["Validate BST", "Range recursion"],
  ["Kth Smallest in BST", "Inorder traversal"],
  ["Lowest Common Ancestor", "BST/tree reasoning"],
  ["Number of Islands", "Grid DFS/BFS"],
  ["Clone Graph", "Graph traversal map"],
  ["Course Schedule", "Topological sort"],
  ["Rotting Oranges", "Multi-source BFS"],
  ["Pacific Atlantic Water Flow", "Reverse DFS"],
  ["Find Median from Data Stream", "Two heaps"],
  ["Merge K Sorted Lists", "Heap"],
  ["K Closest Points", "Heap/quickselect"],
  ["Subsets", "Backtracking"],
  ["Combination Sum", "Backtracking choices"],
  ["Permutations", "Backtracking used set"],
  ["Word Search", "Grid backtracking"],
  ["Climbing Stairs", "1D DP"],
  ["House Robber", "DP state"],
  ["Coin Change", "Unbounded DP"],
  ["Longest Increasing Subsequence", "DP/binary search"],
  ["Longest Common Subsequence", "2D DP"],
  ["Decode Ways", "DP edge cases"],
  ["Unique Paths", "Grid DP"],
  ["Jump Game", "Greedy"],
  ["Meeting Rooms II", "Heap intervals"],
  ["Insert Interval", "Interval merge"],
  ["LRU Cache", "HashMap plus doubly linked list"],
  ["Design Add and Search Words", "Trie DFS"],
  ["Serialize/Deserialize Binary Tree", "Tree encoding"],
  ["Word Ladder", "BFS shortest path"],
  ["Trapping Rain Water", "Two pointers / prefix max"],
  ["Sliding Window Maximum", "Monotonic deque"],
  ["Alien Dictionary", "Graph topo"],
  ["Edit Distance", "2D DP"]
];

export const SYSTEM_DESIGNS: ReadonlyArray<string> = [
  "URL Shortener",
  "Notification Service",
  "Rate Limiter",
  "News Feed",
  "Chat Application",
  "Payment System",
  "Ride Sharing Backend",
  "Distributed Cache",
  "AI Payroll Support Assistant",
  "Market Narrative Digest Engine",
  "The Win List Local-First Sync",
  "Job Application Tracker"
];

export const STAR_STORIES: ReadonlyArray<string> = [
  "Oracle 25% payroll throughput improvement",
  "Oracle 40% API latency reduction",
  "Oracle 4x SQL performance improvement",
  "ADF to REST/Redwood modernization leadership",
  "Kafka/event-driven payroll processing",
  "Absence management high-volume reliability",
  "Samsung Time-To-Full charging feature",
  "Samsung Python/Java log automation",
  "Mentoring juniors and reducing production bugs",
  "Data corruption/client incident resolution under pressure"
];

export const CODING_TOPICS: ReadonlyArray<string> = [
  "Read and summarize Clean Code naming rules; rename one bad local variable in a project branch.",
  "Write a Java checklist for null-safety, immutability, defensive copies, and clear exceptions.",
  "Practice extracting pure functions from JSX-heavy logic using a small example.",
  "Learn reducer pattern; model The Win List task state with actions and invariants.",
  "Review SOLID using Oracle-style service classes; write one example per principle.",
  "Implement Strategy pattern in Java for notification channels or habit scoring.",
  "Implement Factory pattern in Java for task generators or market signal parsers.",
  "Implement Observer pattern for sync/analytics events without coupling UI to services.",
  "Write unit tests for one pure function using arrange-act-assert.",
  "Learn TypeScript discriminated unions and apply to task/action states.",
  "Write SQL index decision notes: when an index helps, hurts, or needs composite order.",
  "Practice API design: idempotency, pagination, validation, and error contract.",
  "Draw cache-aside, write-through, and write-back flow with trade-offs.",
  "Review concurrency basics: thread pool sizing, blocking calls, backpressure.",
  "Write a small design note on local-first data versus always-online sync.",
  "Create a code-review checklist: readability, state ownership, tests, edge cases.",
  "Refactor a sample 80-line function into intent-named helpers.",
  "Practice dependency inversion with a storage interface and local/cloud implementations.",
  "Review accessibility basics: labels, focus states, keyboard navigation, reduced motion.",
  "Write error-state patterns: loading, empty, partial failure, retry, offline.",
  "Model Market Narrative digest generation as command, service, repository layers.",
  "Practice test pyramid thinking: unit, integration, contract, smoke, QA gate.",
  "Write a risk register for your monorepo: auth, secrets, scheduler, data quality.",
  "Review package boundary rules for packages/ui and packages/api-client.",
  "Design a small typed API client with DTO, error, and retry policy.",
  "Practice system design scale estimates with QPS, storage, and read/write ratio.",
  "Write a senior-level trade-off paragraph: modular monolith versus microservices.",
  "Create one ADR template and fill it for local-first sync in The Win List.",
  "Review Java Stream readability: when not to use streams.",
  "Phase checkpoint: write 10 rules you now follow before accepting AI-generated code."
];

export const WEBSITE_MISSIONS: ReadonlyArray<readonly [string, string]> = [
  ["Portfolio evidence audit", "Open Portfolio and create a claim-to-proof table for throughput, SQL speedup, events/hour, REST APIs, and project links."],
  ["Portfolio component map", "Rebuild the Portfolio section model as data objects: experience[], projects[], principles[], skills[]."],
  ["HabitTracker decomposition map", "Read components/HabitTracker.tsx and map every major concern: storage, theme, onboarding, reminders, sync, analytics, UI."],
  ["Extract storage keys", "Create a planned lib/storageKeys.ts and lib/storage.ts split for The Win List localStorage/cookie constants."],
  ["Reducer refactor plan", "Design TrackerAction and TrackerReducer types for completing wins, editing notes, adding habits, and import/export."],
  ["Split Day Board", "Plan components/day/DayBoard.tsx, DayPartSection.tsx, WinCard.tsx, NotePanel.tsx from HabitTracker.tsx."],
  ["Extract useTrackerPersistence", "Move readSavedTrackerState/saveTrackerState/import-export concerns into a custom hook design."],
  ["Extract useCloudSync", "Create a hook boundary around Supabase session, overview, backup status, and consent state."],
  ["AdminConsole audit", "Read components/AdminConsole.tsx and define the minimum dashboard, query layer, and empty/error states."],
  ["habitData.ts normalization", "Audit lib/habitData.ts for constants, types, defaults, and validation; decide what belongs in data versus domain logic."],
  ["primaryWins.ts tests", "Review tests/primaryWins.test.mjs and add 5 missing edge cases around optional/core transitions."],
  ["The Win List UX states", "Design loading, offline, sync failed, empty first day, and perfect-day celebration states consistently."],
  ["Market Narrative archive UX", "Audit marketnarrative.in archive filters and design a clearer source-ledger/card hierarchy."],
  ["Market Narrative source trust", "Design a visible evidence score: official source count, India-source gate, stale-data warning, and source freshness."],
  ["marketNews monorepo map", "Document backend, apps/public-portal, apps/admin-studio, apps/trading-dashboard, packages/ui, packages/api-client boundaries."],
  ["API contract extraction", "Design typed contracts between Spring backend/public portal/admin studio; list DTOs and error states."],
  ["QA gate review", "Read tools/verify.mjs and tools/production-qa-gate.mjs flow; document what each gate proves and what it misses."],
  ["Trading dashboard safety UI", "Design safer UI states for disabled live orders, token expiry, stale market data, loss lockout, and kill switch."],
  ["Shared design tokens", "Create a tokens plan for colors, spacing, card radius, typography, focus rings across all projects."],
  ["Accessibility pass", "Run a manual checklist for labels, contrast, tab order, focus visibility, aria-live, and reduced motion."],
  ["Performance audit", "List bundle, hydration, image, data-fetching, and localStorage performance risks for The Win List."],
  ["Case-study page (Win List)", "Write a proper case study for The Win List: problem, architecture, trade-offs, code before/after, metrics."],
  ["Case-study page (Market Narrative)", "Write a proper case study for Market Narrative: ingestion, clustering, scanner, public portal, QA gate, trade-offs."],
  ["Deploy redesign", "Deploy one small refactor branch or visual improvement and write a 5-line changelog."],
  ["Portfolio integration", "Update Portfolio project cards with screenshots, architecture links, and one honest limitation per project."],
  ["Final reconstruction review", "Record a 5-minute walkthrough explaining the refactors without reading notes."]
];

export const EXPRESS_PLAN: ReadonlyArray<string> = [
  "Run Come to Canada self-screen and save your eligibility result.",
  "Build a CRS scratch sheet with age, education, language, work experience, and funds.",
  "Compare FSW, CEC, and FST; mark FSW as primary unless Canadian experience exists.",
  "Draft your actual Oracle/Samsung duty inventory without inflating coding claims.",
  "Map NOC 21231 versus 21222 and highlight matching duties with evidence.",
  "Research IELTS General vs Academic; write why General Training is required.",
  "Choose IELTS General or PTE Core and create a test-prep score target table.",
  "Search IELTS/PTE test dates near Punjab/Chandigarh and shortlist 3 slots.",
  "Check passport expiry, address details, and name consistency across documents.",
  "Compare WES, CES, IQAS, and ICES for your degree and processing constraints.",
  "Create WES/ECA document checklist: degree, transcript, mark sheets, ID.",
  "Email or portal-check your university transcript process and expected timeline.",
  "Draft Oracle reference letter in IRCC format with duties, salary, hours, dates.",
  "Draft Samsung reference letter in IRCC format with duties and measurable work.",
  "Collect offer letters, appraisal letters, relieving letters, and recent payslips.",
  "Create a clean work experience timeline from Samsung to current Oracle role.",
  "Estimate proof of funds requirement and convert CAD amount to INR buffer.",
  "Create a PR document folder structure with numbered subfolders.",
  "Book or calendar-block IELTS/PTE exam window target.",
  "Start ECA account creation and note document upload/payment steps.",
  "Write a one-page NOC justification memo using evidence from reference letters.",
  "Check if your friends are siblings or only friends; note CRS impact honestly.",
  "Create GCKey/IRCC account readiness checklist; do not submit incomplete profile.",
  "Research latest Express Entry draw types and create a weekly draw log tab.",
  "Research Ontario Human Capital Priorities and tech-related invitation history.",
  "Research BC PNP Tech and whether job offer requirements apply.",
  "Research Alberta Advantage streams and tech pathway constraints.",
  "Research Saskatchewan/Atlantic options and role/offer constraints.",
  "Review document naming convention: employer_documenttype_date.pdf.",
  "Phase 1 checkpoint: CRS estimate, IELTS date plan, ECA path, NOC decision draft.",
  "Submit or finish ECA application steps and save reference number.",
  "Request transcripts officially and log expected delivery date.",
  "Ask Oracle HR/manager what reference-letter format they can provide.",
  "Ask Samsung contact/HR for reference-letter feasibility.",
  "Create backup evidence package if HR refuses detailed duties letter.",
  "Enter IELTS study calendar: Listening, Reading, Writing Task 1/2, Speaking.",
  "Do CRS recalculation with CLB 9 and CLB 10 scenarios.",
  "Check official funds amount again and set savings/bank-letter target.",
  "Create PNP spreadsheet with province, stream, job offer need, CRS history.",
  "Review Ontario NOC relevance and whether your role title/duties align.",
  "Review BC and Alberta cities against job-market/lifestyle preferences.",
  "Draft a Canadian-format technical resume header and immigration-neutral summary.",
  "Create LinkedIn Canada search alerts for Senior Software Engineer and HCM roles.",
  "Prepare reference-letter follow-up emails with exact bullet wording.",
  "Scan all education documents and verify name/date consistency.",
  "Track ECA status; log any missing university action.",
  "Practice filling Express Entry profile sections on paper before online entry.",
  "Review ITA 60-day document window and identify documents that are slow.",
  "Create police certificate timing note: do near ITA, not too early.",
  "Review medical exam timing and panel physician concept.",
  "Research CIC News/IRCC draw update habit and add Wednesday reminder.",
  "Join one serious Express Entry community and save only high-signal posts.",
  "Build employer duty evidence matrix: duty, proof file, NOC match, metric.",
  "Update CRS estimate with any confirmed ECA or language progress.",
  "Prepare Express Entry profile data: addresses, travel, education, work dates.",
  "Create PNP outreach list: recruiters/companies in Ontario, BC, Alberta.",
  "Draft Canadian employer cover letter template: collaborative, concise, factual.",
  "Check funds account health: no borrowed money, stable 6-month average balance.",
  "Phase 2 checkpoint: ECA in progress, IELTS scheduled, reference letters moving.",
  "Create Express Entry profile if IELTS/ECA are ready; otherwise prepare final draft.",
  "Update profile draft with exact NOC and work history dates.",
  "Review profile for mismatch between title and duties before submission.",
  "Check IRCC draw result and log cutoff/type/invitations.",
  "Submit profile when language and ECA data are available and verified.",
  "Create profile-live routine: weekly draw check and monthly CRS recalculation.",
  "Register or prepare interest for relevant PNP streams where eligible.",
  "Create job-offer strategy for PNP: target employers, provinces, role titles.",
  "Prepare settlement narrative: why province/city, friends/network, job fit.",
  "Audit all PDF scans for clarity, file size, date, and naming.",
  "Prepare proof-of-funds bank-letter request draft for your bank.",
  "Prepare police certificate appointment steps but wait for timing trigger.",
  "Create ITA emergency checklist: tasks due in first 7 days after invitation.",
  "Review misrepresentation risks: do not overstate coding duties or job title.",
  "Confirm no gaps in personal/work history need explanation.",
  "Run final CRS scenarios: current, CLB 10, PNP, French NCLC 7 future.",
  "Create Canada landing budget draft: rent, deposit, job-search runway, emergency fund.",
  "Create PR plan B: India switch, PR, Master's, direct job - compare triggers.",
  "Check ECA result/status and update profile plan accordingly.",
  "Check IELTS result/status or final mock scores and decide retake threshold.",
  "Review PNP streams again for changed draw patterns or occupation lists.",
  "Prepare post-ITA forms checklist: travel, address, family, work, education.",
  "Collect digital photo specs and local studio shortlist.",
  "Update reference-letter evidence with final signed versions or alternatives.",
  "Create final Express Entry folder audit and missing-doc list.",
  "Send one Canadian-market application/referral message tied to PR pathway.",
  "Check IRCC draw and write a 5-line interpretation of where your CRS stands.",
  "Create final Day 90 PR dashboard: CRS, documents, risks, next 30-day actions.",
  "Decide next immigration move: profile live, PNP push, French, or Master's research."
];

export const DOCUMENT_CHECKLIST: ReadonlyArray<readonly [string, string]> = [
  ["Passport validity", "Check expiry and renew early if it expires during the PR process."],
  ["CRS worksheet", "Save your age, education, IELTS target, work history, and estimated CRS."],
  ["NOC evidence", "Prepare duty mapping for 21231 vs 21222 using real Oracle/Samsung duties."],
  ["IELTS General or PTE Core booking", "Use Express Entry accepted test, not IELTS Academic."],
  ["IELTS result / TRF", "Keep result number ready for profile creation."],
  ["ECA account", "Create WES/CES/IQAS account and save reference number."],
  ["Degree certificate", "Scan front/back and keep original ready."],
  ["Transcripts / mark sheets", "Request sealed/university-uploaded documents as required by ECA org."],
  ["Oracle reference letter", "Letterhead, title, dates, hours/week, salary, duties, supervisor contact."],
  ["Samsung reference letter", "Same IRCC format; support duties with offer/relieving letters if needed."],
  ["Payslips and Form 16", "Collect proof for each work period claimed."],
  ["Offer and relieving letters", "Keep PDFs named by employer and date."],
  ["Proof of funds", "Bank letter with current balance, average 6-month balance, debts, account open date."],
  ["Police clearance certificate", "Understand PSK process; do closer to ITA because validity is time-sensitive."],
  ["Medical exam awareness", "Panel physician/eMedical happens after ITA or upfront if instructed."],
  ["Digital photos", "Prepare IRCC-spec photo once ITA is close."],
  ["GCKey / IRCC account", "Create and secure account before profile submission."],
  ["PNP tracker", "Track Ontario, BC, Alberta, Saskatchewan, and Atlantic options."],
  ["Draw log", "Record round date, type, invitations, cutoff CRS every week."],
  ["Application tracker", "Log global/Canada roles weekly after Week 5."]
];
